version: "3"
services:
  jenkins-docker:
    image: docker:dind
    privileged: true
    ports:
      - "2376:2376"
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - "jenkins-docker-certs:/certs/client"
      - "jenkins-data:/var/jenkins_home"
    networks:
      jenkins:
        aliases:
          - docker
  jenkins-blueocean:
    image: jenkins-blueocean:lts-jdk11
    build: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - "jenkins-docker-certs:/certs/client:ro"
      - "jenkins-data:/var/jenkins_home"
    networks:
      - jenkins
  splunk:
    image: splunk/splunk:latest
    ports:
      - "8000:8000"
    environment:
      SPLUNK_PASSWORD: password
      SPLUNK_START_ARGS: --accept-license"
    volumes:
      - "splunk-var:/opt/splunk/var"
      - "splunk-etc:/opt/splunk/etc"
    networks:
      - splunk
networks:
  jenkins:
  splunk:
volumes:
  jenkins-docker-certs:
  jenkins-data:
  splunk-var:
  splunk-etc:
